### ISSUE TITLE
about the implementation of NGSI-LD

### ISSUE THREAD

**Issue by showersky** [smartfog/fogflow#101]
I had a look at the internal data structured defined to represent an NGSI-LD entity. I have a question about the list of properties and relationships. Could we present them as a map rather than a list? From the performance perspective, using map is more efficient. But this requires each property/relationship to have a unique name. 

I like to know how you think of this.

**Comment by martin-p-bauer** [comment]
Be aware of the support for multi-attributes in NGSI-LD, i.e. multiple instances of the same property or relationship. For exmaple, the speed of a car may be provided by the speedometer and the GPS independently and there are two separate instances of the property speed in the system. They can be individually identified by a datasetId. There can be one default instance without such a datasetId.

**Comment by showersky** [comment]
good point. Is this

**Comment by martin-p-bauer** [comment]
They are independent property instances, i.e. each can have its own properties or relationships (of property).
So it is not the same as a property with a value that is an array!

**Comment by showersky** [comment]
Thanks for the information. Yes, we need to take this into account as well.

**Comment by showersky** [comment]
I see the following example for multi-attributes. Since there are still two different keys, I do not see the problem with using Map as the internal data structure to save all properties/relationships. 

{
  "id": "urn:ngsi-ld:Vehicle:A4567",
  "type": "Vehicle",
  "speed#1": {
    "type": "Property",
    "value": 55,
    "source": {
      "type": "Property",
      "value": "Speedometer"
    },
    "datasetId": "urn:ngsi-ld:Property:speedometerA4567-speed"
  },
  "speed#2": {
    "type": "Property",
    "value": 54.5,
    "source": {
      "type": "Property",
      "value": "GPS"
    },
    "datasetId": "urn:ngsi-ld:Property:gpsBxyz123-speed"
  },
  "@context": [
    {
      "speed#1": "http://example.org/speed",
      "speed#2": "http://example.org/speed",
      "source": "http://example.org/hasSource"
    },
    "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"
  ]
}

**Comment by martin-p-bauer** [comment]
Hi Bin,

This representation is no longer valid in the upcoming NGSI-LD v1.3.1 specification.
Scorpio already implements the new representation, which is based on a
single property / relationship name with an array of properties /relationships as value.

"friend": [
    {
        "type": "Relationship",
        "object": "urn:person:Sam",
        "datasetId": "urn:myspecialfriendid1234567",
        "friendInfo": {
            "type": "Property",
            "value": {
                "nickname": "Sammy",
                "age": 22,
                "description": "Best-friend"
            }
        }
    },
   {
        "type": "Relationship",
        "object": "urn:person:Victoria",
        "datasetId": "urn:myspecialfriendid9876543",
        "friendInfo": {
            "type": "Property",
            "value": {
                "nickname": "Vicky",
                "age": 25
            }
        }
    }
]

Martin

**Comment by showersky** [comment]
Hi Martin, 
do you have some request examples of how those multi-properities/relationships are created/updated/accessed? How to differentiate them when updating the value of one particular property? by specifying the datasetId?

**Comment by showersky** [comment]
close this discussion and we are currently experimenting an approach to address this issue.
