### ISSUE TITLE
integration with Kubernetes

### ISSUE THREAD

**Issue by showersky** [smartfog/fogflow#103]
FogFlow works with the APIs provided by Docker Engine. This is suitable for constrained low-end edge devices like Raspberry Pi or IoT Gateway. However, for more advanced edge gateway or cloud nodes, Kubernetes is more popular and we can consider to integrate FogFlow with Kubernetes.

**Comment by showersky** [comment]
I have looked into the API of Kubernetes. The integration with Kubernetes API will come into our agenda after the current release. Since Kubernetes has been the most popular orchestration framework for general applications, (k8s for the cloud part and k3s for the edge part), it is now the perfect time to do this type of integration.

**Comment by naveennec** [comment]
kubernetes support is added in cloud as well as edge with RBAC support
