### ISSUE TITLE
[SHOULD] Double tag FIWARE Release

### ISSUE THREAD

**Issue by jason-fox** [smartfog/fogflow#11]
Please add an additional tag to  72d9eea to indicate that it was included as part of FIWARE 7.5.1 - you can see a similar examples here:

[IoT Agent JSON](https://github.com/telefonicaid/iotagent-json/releases)

Also double tag 1760f1c  to indicate that it was included as part of FIWARE 7.5 and FIWARE 7.4

**Comment by showersky** [comment]
those tags have been created

**Comment by showersky** [comment]
this issue has been addressed.
