### ISSUE TITLE
designer is not able to load metadata from dgraph if dgraph server is started but not ready to serve requests

### ISSUE THREAD

**Issue by showersky** [smartfog/fogflow#113]
this is a problem with the order of launching all FogFlow components via docker-composer. If dgraph is started first but still does not get ready for requests, designer will fail to load metadata (fog functions, service topologies) from dgraph for the initialization phase. 

We need to find a re-try mechanism for the queryForEntity function of Designer.

**Comment by sanchitanec** [comment]
Hi showersky, added a re-try mechanism for queryForEntity function of Designer.
This will re-try untill Dgraph services ready for request.
