### ISSUE TITLE
[MUST] Docker Images not clearly linked and available

### ISSUE THREAD

**Issue by jason-fox** [smartfog/fogflow#12]
There is a mismatch between the docker images produced in the repository  and the listings elsewhere

* According to [DockerHub](https://hub.docker.com/u/fogflow), Fogflow produces 16 images.
* According to the `README` only 1 image  `fogflow/discovery` is badged for pulls.
* According to the FIWARE [Catalogue](https://github.com/Fiware/catalogue/tree/master/processing) no docker images are listed

Looking in the [docker/README](https://github.com/smartfog/fogflow/blob/master/docker/README.md), 5 images are listed.

It is  unclear which of these is correct.

If you look at [Cygnus](https://github.com/telefonicaid/fiware-cygnus), you will see that all Docker Images are mentioned and listed in the `README`

**Comment by showersky** [comment]
Hi Json,

FogFlow has 5 docker images, as described in [docker/README](https://github.com/smartfog/fogflow/blob/master/docker/README.md). 

I do not know how to deal with the badge. You told me that I should choose the one with the highest number of pulls.

**Comment by showersky** [comment]
Hi Json, 

Could you update the docker images of FogFlow on the FIWARE [Catalogue](https://github.com/Fiware/catalogue/tree/master/processing) according to [docker/README](https://github.com/smartfog/fogflow/blob/master/docker/README.md)?

**Comment by showersky** [comment]
Thanks. I did it like OpenMTC. It has been updated. Anything else is required for this issue? Otherwise, I will close this issue.

**Comment by jason-fox** [comment]
@showersky - I have corrected the catalogue and raised a PR to add the link box.
