### ISSUE TITLE
Broker should take decision according to watched attributes in NGSILD notification of an entity. 

### ISSUE THREAD

**Issue by Neeraj-Nec** [smartfog/fogflow#126]
At this time of implementation in NGSILD broker notify all the created attributes of a entity for any update request . Broker should take decision according to  the watched attribute and notification condition.

**Comment by showersky** [comment]
For NGSI v1, this is already supported, I think. To be checked...

**Comment by Necuser1** [comment]
NGSIV1 subscription request  does not have condition in fogflow.

**Comment by Neeraj-Nec** [comment]
Done
