### ISSUE TITLE
CNCF-Runtime discussion/presentation(?)

### ISSUE THREAD

**Issue by raravena80** [smartfog/fogflow#130]
Hello Fogflow team,

I'm one of the co-chairs of the CNCF SIG-Runtime. I'm reaching out and I think it would be great for you to present/discuss the project at one of our meetings. For example, a general overview of the project and its use cases. I'm aware that the project is part of FIWARE, but I still believe it would be great to get an overview.

Let me know if this something you'd be interested in doing. If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-sig-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by showersky** [comment]
Hi @raravena80, 

Yes, we are happy to present and discuss FogFlow at your upcoming meetings. I added my presentation into the agenda on Oct. 17th. The presentation slides will be shared a few days before the meeting.
