### ISSUE TITLE
improve the tutorial on how to change the configuration file according to the user environment

### ISSUE THREAD

**Issue by smartfog** [smartfog/fogflow#132]
The current tutorial is still confusing to the users who need to change the deployment configuration file according to their own setup environment. It is necessary to clearly introduce how to do this with a system diagram.

**Comment by showersky** [comment]
it is simplified to have only one hostip in the configuration for the single-node setup. The other two ips: 1) coreservice_ip is required only by the edge node; 2) external_ip is only needed when the edge node is behind NAT. The tutorial will be updated accordingly in the master branch.
