### ISSUE TITLE
Broker not working after Discovery down

### ISSUE THREAD

**Issue by nak2k** [smartfog/fogflow#134]
Hi.

I think that entities and subscriptions are lost when FogFlow Discovery goes down.
If that happens, do I need to restart FogFlow Broker and Topology Master after restarting FogFlow Discovery?

Is there any other way to recover?

**Comment by Necuser1** [comment]
yes broker will not work if discovery will goes down . because all broker register on discovery . And you need to restart all the component again .

**Comment by Necuser1** [comment]
If you have created fogflow internal entities (like fogFunction , operator, dockerimage  etc   )from designer then only you can restore .

**Comment by nak2k** [comment]
Thank you for quick replying.

Do you know if there are any development plans to improve durability, such as persistence of internal entities?
Or will such a feature not be implemented in the future due to performance focus?

**Comment by Necuser1** [comment]
yes , you are correct because of performance issue fogflow does not have any database .

**Comment by Necuser1** [comment]
But if you are talking about forflow internal entities then we have dgraph connected with designer . please study Fogflow document  https://fogflow.readthedocs.io/en/latest/core_concept.html#fogflow-storage

**Comment by nak2k** [comment]
Thank you. My questions are resolved.
