### ISSUE TITLE
[MUST] Every GE must have training materials

### ISSUE THREAD

**Issue by jason-fox** [smartfog/fogflow#14]
At the moment this enabler has no Tutorial and no link to the Academy and does not fulfil the minimum **Training** section requirements.  There are no FogFlow training materials to be found in the [Academy](https://fiware-academy.readthedocs.io/en/latest/) 

The suggestion is to create a simple *FogFlow to Orion tutorial*  to provide a series of simple hello world connections for simple processing - this needs to include 

* One docker compose file for base config
* A piece of code to enable Fog computing
* An indication on how to make  minimal measure arrive (e.g. publishing an MQTT topic or equivalent)
* Proof that the data arrives in Orion.

- Presence of training  is a MUST requirement

**Comment by showersky** [comment]
It is a good suggestion. We will soon prepare the tutorial you suggested. 
By the way, where is this tutorial supposed to be released? Do you have an example or template for this tutorial?

**Comment by jason-fox** [comment]
The [FIWARE Academy](https://fiware-academy.readthedocs.io) holds a list of all training materials, videos, slide decks, links to sample code etc, for example [Kurento](https://fiware-academy.readthedocs.io/en/latest/processing/kurento/index.html) offers all three. If you are writing sample code see https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN/issues/38 as an example of compliance for an IoT Agent for the **Academy** Requirement. For Slides or videos just add a PR to the Academy [Repo](https://github.com/Fiware/academy)

The **Tutorial** Requirement is stricter - offering a Dockerized environment showing use of the component with a relevant code commentary - [FIWARE 503: Introduction to Media Streams](https://fiware-tutorials.readthedocs.io/en/latest/media-streams). I would expect the tutorials to use rather than duplicate existing materials. A similar example  or reuse of resources can be found for [Fast-RTPS](https://fiware-tutorials.readthedocs.io/en/latest/fast-rtps-micro-rtps/index.html)

The aim is to collate all _Official_ FIWARE tutorials under a FIWARE umbrella [repo](https://github.com/Fiware/tutorials.Step-by-Step). Company specific stuff would remain on your side (for example the relevant Kurento example code is a submodule within the [Media Streams](https://github.com/Fiware/tutorials.Media-Streams) tutorial repo.

**Comment by smartfog** [comment]
the FogFlow tutorial is finished. Please find the first draft [here](https://github.com/smartfog/fogflow/blob/master/doc/tutorial/fogflow.md)
