### ISSUE TITLE
[SHOULD] run tests on CI - test suite missing

### ISSUE THREAD

**Issue by jason-fox** [smartfog/fogflow#15]
A test suite is currently missing from the public codebase for this GE, and the tests should be run on CI. The standard GO testing framework is suceeding because no tests are present.

```
$ go test -v ./...
?   	github.com/smartfog/fogflow/master	[no test files]
The command "go test -v ./..." exited with 0.
```

* Running tests on CI is a TSC SHOULD requirement

**Comment by sanchitanec** [comment]
The issue has been fixed, Golint is integrated with travis.yml to check coding style mistakes during code commit..
The output can be checked trav-CI site: https://travis-ci.com/.
