### ISSUE TITLE
update system monitoring

### ISSUE THREAD

**Issue by showersky** [smartfog/fogflow#165]
After checking the system monitoring part with metricbeat, elasticsearch, and Grafana, I identified the following issues.  We need to make this part optional, due to the following reasons: 1) this will further add some complexity of beginners to set up the FogFlow system; 2) the current setup still requires some effort to configure and setup the data source properly; 3) the system monitoring itself will consume some resource. 

Please consider to update the system monitoring part of the tutorial. This part can explain what the users can do if they want to enable the system monitoring features. Also, we should further reduce the effort from the users. It is better to load the configuration of Grafana without asking the users to configure the Grafana dashboard.

**Comment by naveennec** [comment]
its updated, one new section is created in manual for with auto configuring.  its merged in fogflow development branch.
