### ISSUE TITLE
performance evaluation of the thinBroker in FogFlow

### ISSUE THREAD

**Issue by showersky** [smartfog/fogflow#166]
The current FogFlow version has implemented a light-weight NGSI-LD broker with limited NGSI-LD interface support for data exchange between FogFlow applications. It is supposed to provide low latency and high throughput. We need to evaluate this part of feature via a Jmeter benchmark test. Please consider to extend https://github.com/smartfog/fogflow/blob/development/test/jmeter/ngsi-ld/ngsi-ld-fogflow.jmx for this purpose.

**Comment by Neeraj-Nec** [comment]
Creating Document for performance analysis.
Basic introduction and environment setup document creation has been done

**Comment by Neeraj-Nec** [comment]
Resolved and documentation has been merged.
Link of Document: https://github.com/smartfog/fogflow/blob/development/doc/en/source/performanceNew.rst
