### ISSUE TITLE
Add FogFlow to tour guide

### ISSUE THREAD

**Issue by jason-fox** [smartfog/fogflow#19]
As FogFlow moves to Full GE membership, it needs a section in the FIWARE [Tour Guide](https://fiwaretourguide.readthedocs.io/en/latest/) - see https://github.com/Fiware/docs.TourGuide/issues/81

A tour guide entry should be a brief getting started, typically a single page describing usage based on the assumption that the product is up and running. There should be no docker-compose set-up and it can be assumed that the product is already connected with a context broker instance.

Good examples with an appropriate level of detail which follow the template can be found here:

* [Cygnus](https://github.com/Fiware/docs.TourGuide/blob/master/docs/core/cygnus/introduction.md)
* [Draco](https://github.com/Fiware/docs.TourGuide/blob/master/docs/core/draco/introduction.md)
* [IoT Agents](https://github.com/Fiware/docs.TourGuide/tree/master/docs/iot-agents)

It doesn't need to be long  -  it is effectively a teaser -  a simple demonstration of the sort of thing FogFlow can do so that readers can move on to the full documentation if interested. 

Please fork https://github.com/Fiware/docs.TourGuide and raise a PR adding your files under  ./docs/processing/fogflow

**Comment by smartfog** [comment]
the initial version is provided by a PR.
