### ISSUE TITLE
integration with NGSI-LD based IoT Agent(s) at the FogFlow Edge Node

### ISSUE THREAD

**Issue by showersky** [smartfog/fogflow#212]
We need to check the status of NGSI-LD IoT Agent(s). If they are ready to convert other protocols (e.g., MQTT) into NGSI-LD at the edge side, we can integrate them into the FogFlow edge node as well and then update the tutorial to show how it can work.

**Comment by showersky** [comment]
It seems the changes and test have been done. Is there any instruction to try and test this part?

**Comment by Neeraj-Nec** [comment]
issue resolved and merged in development branch
