### ISSUE TITLE
IP Configuration documentation should include the used port and firewall related information.

### ISSUE THREAD

**Issue by naveennec** [smartfog/fogflow#239]
(Stellio and FogFlow integration) EGM suggestion:-
We encountered some problems at the beginning with ports blocked by a local firewall. Maybe it could worth adding a section at the beginning explaining all the ports that have to be opened (and for which component)

**Comment by pradumnnec** [comment]
Suggestion is incorporated at right position within the tutorial. The information about the needed ports is included in tutorial along with a diagrammatic representation of Fogflow components along with default ports.
