### ISSUE TITLE
use multi-stage build to create the docker images of all FogFlow components 

### ISSUE THREAD

**Issue by showersky** [smartfog/fogflow#253]
this is now a SHOULD requirement for all FIWARE GEs. Please refer to the information here https://docs.docker.com/develop/develop-images/multistage-build/

**Comment by naveennec** [comment]
Thank you Bin, We have started working on it.

**Comment by pradumnnec** [comment]
We will maintain the multi-stage build file for creating docker images. Using this build file, user will not be bound on his host environment for dependencies like golang, Node, npm.                                                                                                                                            For faster image creation we can have another build which would help in development processes for Fogflow.

**Comment by pradumnnec** [comment]
The pull request regarding the issue fix has been made and merged in development branch.

This pull Id is mentioned below : 
https://github.com/smartfog/fogflow/pull/267

The fix involves following changes : 

1. The discovery folder contains two Dockerfiles :
     a) Dockerfile_multistage - this file creates docker image for discovery using multistage process and is independent of environment.
     b) Dockerfile_development - this creates docker image for discovery  and is used for development purpose.
     c) build.sh - this creates the docker image using above Dockerfiles. 
          Eg. :-  sh build development / sh build multistage

2. The broker folder contains two Dockerfiles :
     a) Dockerfile_multistage - this file creates docker image for broker using multistage process and is independent of environment.
     b) Dockerfile_development - this creates docker image for broker and is used for development purpose.
     c) build.sh - this creates the docker image using above Dockerfiles. 
          Eg. :-  sh build development / sh build multistage

3. The designer folder contains two Dockerfiles :
     a) Dockerfile_multistage - this file creates docker image for designer using multistage process and is independent of environment.
     b) Dockerfile_development - this creates docker image for designer and is used for development purpose.
     c) build.sh - this creates the docker image using above Dockerfiles. 
          Eg. :-  sh build development / sh build multistage

4. The  master folder contains two Dockerfiles :
     a) Dockerfile_multistage - this file creates docker image for master using multistage process and is independent of environment.
     b) Dockerfile_development - this creates docker image for master and is used for development purpose.
     c) build.sh - this creates the docker image using above Dockerfiles. 
          Eg. :-  sh build development / sh build multistage

5. The worker folder contains two Dockerfiles :
     a) Dockerfile_multistage - this file creates docker image for worker using multistage process and is independent of environment.
     b) Dockerfile_development - this creates docker image for worker and is used for development purpose.
     c) build.sh - this creates the docker image using above Dockerfiles. 
          Eg. :-  sh build development / sh build multistage
