### ISSUE TITLE
k8s Update : Deletion of pods and services created as  task.

### ISSUE THREAD

**Issue by naveennec** [smartfog/fogflow#271]
Need to implement the logic for how to delete the pods for task which are no more in use.
Need to add code in k8s client to achieve the task.

**Comment by Pradumn-18** [comment]
Issue is resolved. 

The pods that are launched in correspondence to task instances can now be deleted and its associated service is also removed by the Fogflow worker, as per the flow and inputs received the worker.

**Comment by showersky** [comment]
Is this already merged into the development branch? Where could I validate this feature? Any documentation?

**Comment by pradumnnec** [comment]
Raised a Pull Request for same.

https://github.com/smartfog/fogflow/pull/283

Currently working on documentation for this enhancement and shall inform about its Pull Request soon.

**Comment by pradumnnec** [comment]
Issue #271 is fixed and merged. Documentation in progress.

**Comment by pradumnnec** [comment]
Documentation has been merged and can be viewed on https://github.com/smartfog/fogflow/blob/development/doc/en/source/k8sIntegrationYAML.rst
