### ISSUE TITLE
Revalidate Master : Check consistency of Master with available workers

### ISSUE THREAD

**Issue by pradumnnec** [smartfog/fogflow#277]

**Comment by showersky** [comment]
@pradumnnec , I today checked this problem. In my test, if I stop one edge node, the corresponding

**Comment by showersky** [comment]
Indeed, the onTimer function in master.go needs to check and update the list of workers. I will try to fix this problem soon.

**Comment by showersky** [comment]
I am currently working on a new branch to fix this problem.

**Comment by naveennec** [comment]
This issue is already fixed long back.
