### ISSUE TITLE
new case to be checked with Master and Worker

### ISSUE THREAD

**Issue by showersky** [smartfog/fogflow#282]
For the anomaly detection application, if a new edge is added after the service topology is launched, the output of the anomaly detector task on this new edge is not subscribed by the "counter" task to aggregate the outputs of all anomaly detector tasks for the final counting. We need to check how "ADD_INPUT" is handled by the worker and why the subscription to the newly added input is not issued by the worker.

**Comment by pradumnnec** [comment]
Issue has been fixed in Master and Worker communication. 

The pull request has been raised for the same (https://github.com/smartfog/fogflow/pull/285).

The new changes has been validated.

**Comment by pradumnnec** [comment]
The Pull Request #285 is merged and issue is resolved.
