### ISSUE TITLE
better organize the deployment scripts

### ISSUE THREAD

**Issue by smartfog** [smartfog/fogflow#322]
Currently, we have three options to deploy FogFlow. Those deployment scripts are located at different places in different folder. It is better to organize all of them into the "deployment" folder with a clean and clear structure. 

for example, we can organize them as below. 

```
deployment
       /kubernets
                /cloud-node
               /edge-node
       /helm
                /cloud-node
               /edge-node
       /docker
                /cloud-node
               /edge-node

```

**Comment by naveennec** [comment]
This has been implemented in below commit
https://github.com/smartfog/fogflow/pull/330

**Comment by showersky** [comment]
As this has been addressed, could I remove some duplicated folders and close this open issue?

**Comment by naveennec** [comment]
Please give us few more time, double checking the other folders, don't want to loose any extra scripts present in old folder.

**Comment by showersky** [comment]
Ok. Let's do the cleanup after we finish updating the tutorial.

**Comment by naveennec** [comment]
all the suggestions are implemented. So closing this issue.
