### ISSUE TITLE
Error to download operator docker image.

### ISSUE THREAD

**Issue by hhayashiool** [smartfog/fogflow#33]
I'm trying to test the multi-node FogFlow environment for  "[USE CASE ON ANOMALY DETECTION](https://fogflow.readthedocs.io/en/latest/example2.html)".
multi-node means Cloud node , Edge and device node are different node.

We have used raspberry pi for  Edges and devices.Our environment built a Cloud Node, two Edge Nodes, and three PowerPanel devices. the environment is same as #32  

We found a problem that operator container in the Edge fail to launch.  The Edge's worker log is as bellows.

```bash
$ docker logs edgeworker
INFO: 2019/07/11 01:29:34 annouce myself to the nearby broker
2019/07/11 01:29:35 [*] Waiting for messages. To exit press CTRL+C
INFO: 2019/07/11 01:38:01 execute task  AnomalyDetector.c7cf3f9c-86ef-44d7-baae-d7539915e466  with operation
INFO: 2019/07/11 01:38:01 task configuration {ID:AnomalyDetector.c7cf3f9c-86ef-44d7-baae-d7539915e466 ServiceName:anomaly-detection TaskType: TaskName:AnomalyDetector FunctionCode: DockerImage: WorkerID:Worker.2.3 IsExclusive:false PriorityLevel:50 Status: Inputs:[{Type:PowerPanel Streams:[Stream.PowerPanel.03] URLs:map[]} {Type:Rule Streams:[] URLs:map[]}] Outputs:[{Type:Anomaly StreamID:Stream.Anomaly.03 Annotations:[]}]}
INFO: 2019/07/11 01:38:01 task runnable =  true
INFO: 2019/07/11 01:38:01 to execute Task  AnomalyDetector.c7cf3f9c-86ef-44d7-baae-d7539915e466  to perform Operation
INFO: 2019/07/11 01:38:01 operator image  does not exist locallyoptions : {Username: Password: Email: ServerAddress: IdentityToken: RegistryToken:}options : {Repository: Tag:latest Registry: OutputStream:<nil> RawJSONStream:falseInactivityTimeout:0s Context:<nil>}
ERROR: 2019/07/11 01:38:01 executor.go:137: failed to pull this image , error no such image
ERROR: 2019/07/11 01:38:01 executor.go:282: failed to fetch the image
```

I think Edge's worker can't know operator docker image name.

If you have seen this error, Please teach me How to solve or Could you let me how to debug .

**Comment by smartfog** [comment]
Yes, there is some problem with the location of your operator docker image. From the log, I can see that the edge node on the raspberry pi does not have the correct docker image name. 

By default, the FogFlow dashboard only initialize the operator (anomaly) for x86-based linux, but the docker image for arm-based linux is missing. You need to do the following steps: 

- on your raspberry pi, you need to build this anomaly operator again; 
- from the FogFlow dashboard, you need to register the docker image you built for the same operator "anomaly", but please specify this image is for ARM-based OS; one operator can be mapped to multiple docker images for different hardware/OS types;

After this two steps, you can test it again. In this case, the required docker images are already saved the local file system of your edge nodes and you need to build the docker image on both edge nodes. The other way is to publish your arm-based docker image to docker registry. Then you need to register this docker image using its reference name at Docker Registry. 

In the end, you should be able to see the docker image name in the following log
"INFO: 2019/07/11 01:38:01 task configuration {ID:AnomalyDetector.c7cf3f9c-86ef-44d7-baae-d7539915e466 ServiceName:anomaly-detection TaskType: TaskName:AnomalyDetector FunctionCode: DockerImage: WorkerID:Worker.2.3 IsExclusive:false PriorityLevel:50 Status: Inputs:[{Type:PowerPanel Streams:[Stream.PowerPanel.03] URLs:map[]} {Type:Rule Streams:[] URLs:map[]}] Outputs:[{Type:Anomaly StreamID:Stream.Anomaly.03 Annotations:[]}]}". 

Right now, it is just empty. 

With the docker name, the worker will try to find it from the local docker image repository. If it does not find it, it will search the image from the public docker registry. If you configure the worker with your private user account on docker registry, the worker can search the image from your private docker registry as well.

**Comment by hhayashiool** [comment]
Thank you for  providing suitable advice

I try to do as follwings.

1.  Building anomaly operator docker image on raspberry pi(two Edge nodes).
2. Resist anomaly operator docker image  on fogflog in Cloud Node.

We can run anomaly container image on raspberry pi


```bash
pi@raspberrypi:~/fogflow $ docker ps
CONTAINER ID        IMAGE                    COMMAND             CREATED             STATUS              PORTS                    NAMES
f963e824524d        fogflow/anomaly:latest   "node main.js"      44 seconds ago      Up 39 seconds                                gracious_villani
043eb3b2eeb8        fogflow/worker:arm       "/worker"           6 minutes ago       Up 6 minutes                                 edgeworker
7132dbc61b77        fogflow/broker:arm       "/broker"           6 minutes ago       Up 6 minutes        0.0.0.0:8080->8080/tcp   edgebroker
pi@raspberrypi:~/fogflow $ 
```

Thank you

**Comment by YujiAzama** [comment]
@showersky @smartfog 
Hi,
This is a common issue for users of Raspberry.
I could not find these steps in the FogFlow documentation.
Please add these steps to documentation.
