### ISSUE TITLE
How to fix a Task to a given Worker?

### ISSUE THREAD

**Issue by thiagopereirasilva** [smartfog/fogflow#35]
How to fix the execution of a Task in a given Worker?
For example, if an accelerator hardware attached to Worker.03 and a particular Task must be executed on it.

**Comment by smartfog** [comment]
not sure if you DO want to fix the execution of a specific task on a specific worker. The current design does not support this fixed task assignment. However, we are changing the code to support this in a different way. On the one hand, we are adding addition features to represent the capability of workers; on the other hand, we ask the operator developer to specify if this operator required to be executed on an Accelerator such as Google Edge TPU. Given these two, the new version will be able to match tasks with proper worker.

**Comment by thiagopereirasilva** [comment]
Is there any prediction of when these features (capability of workers and specify operator required to be executed on an Accelerator) will be available?

**Comment by showersky** [comment]
Sorry. I will try to bring this feature in as soon as possible. Hopefully, next week.

**Comment by smartfog** [comment]
this has been addressed.
