### ISSUE TITLE
create NGSI-LD based device entities

### ISSUE THREAD

**Issue by showersky** [smartfog/fogflow#351]
Please update the device registration page to create new devices based on NGSI-LD so that we can also trigger a NGSI-LD fog function via the dashboard. 

We can add one item to represent the protocol type (NGSI v1, NGSI-LD) so that we can register new device entities either based on NGSI v1 or NGSI-LD. 

https://fogflow.readthedocs.io/en/latest/_images/device-registration.png

**Comment by showersky** [comment]
any idea why the old way of device registration and device query does not work?

**Comment by naveennec** [comment]
Designer dashboard is creating below payload
{
"entityId": {
"id": "Device.Temperature.8d6899a5-07ba-4f5c-b670-343df0362c25",
"type": "Temperature",
"isPattern": false
},
"attributes": {
"DeviceID": {
"type": "string",
"value": "8d6899a5-07ba-4f5c-b670-343df0362c25"
},
"url": {
"type": "string",
"value": "http://192.168.1.11:8080/photo/null"
},
"iconURL": {
"type": "string",
"value": "/photo/defaultIcon.png"
}
},
"metadata": {
"location": {
"type": "point",
"value": {
"latitude": 35.663672208414916,
"longitude": 139.3286129459739
}
}
}
}

**Comment by naveennec** [comment]
This issue in merged in below pull request.
https://github.com/smartfog/fogflow/pull/365/files
Hence closing it.
