### ISSUE TITLE
Cannot use any property conaining "id" within it such as "humidity"

### ISSUE THREAD

**Issue by flaviocirillo** [smartfog/fogflow#358]
Hello,

I cannot use a property containing "id" as the property name because at the following line it is checked the substring "id". 

https://github.com/smartfog/fogflow/blob/1df12f1bb04453d610e1ddbc02d4586445263061/broker/serializer.go#L17

For example, I cannot use "humidity".

**Comment by naveennec** [comment]
this issue is resolved with Issue 373. So closing it.
