### ISSUE TITLE
case insensitive check not comprising all the cases

### ISSUE THREAD

**Issue by flaviocirillo** [smartfog/fogflow#359]
Hello,

at the following line it is checked only two possible configuration of case insensitive such as "GeoProperty" and "geoproperty":
https://github.com/smartfog/fogflow/blob/1df12f1bb04453d610e1ddbc02d4586445263061/broker/serializer.go#L134

The same applies for the following lines.
I would suggest to use a more robust approach: https://stackoverflow.com/questions/44595669/does-go-have-a-case-insensitive-string-contains-function

Further, I think it would be more advisable to have an equals check and not a contains for these cases.

**Comment by Neeraj-Nec** [comment]
Thanks for update @flaviocirillo 

Actually we are working on this issue 

please refer https://github.com/smartfog/fogflow/tree/issue_302 

 As of now we are working and testing with default context only . we will update you once this part will be finish

**Comment by Neeraj-Nec** [comment]
Resoled and merged in development branch with default context

**Comment by naveennec** [comment]
As everything is working fine now so closing this issue.
