### ISSUE TITLE
Can the Tasks that make up a service topology run on different architectures?

### ISSUE THREAD

**Issue by thiagopereirasilva** [smartfog/fogflow#36]
Can the **Tasks** that make up a service topology run on different architectures?

We have a fog infrastructure formed by three Works (one Raspberry Pi 4, one notebook, and a virtual machine). We created a service topology with two Tasks. We registered two Operators, only one of which is for ARM architecture. However when we fire an Intent the FogFlow orchestrator tries to run both Tasks on the Worker located in Raspberry. Obviously the docker image for X86 architecture does not run properly in Raspberry.

**Comment by smartfog** [comment]
By design, one operator can be linked with multiple images, each of which could be used for one specific hardware architecture. Therefore, after you define the operator, you need to register multiple docker images for the same operator. On the other hand, FogFlow master will tell worker which image to use according to the work profile. We will do more test for this part. Thanks for your feedback.

**Comment by thiagopereirasilva** [comment]
I my case I defined one operator and linked it to only one image for X86. However FogFlow master always tell worker in raspberry to use this image. We are trying to use raspberry 4. Did you test fogflow in this new model? How can I check the worker profile to assure that FogFlow master knows the worker as an ARM architecture?
Thanks

**Comment by rahafrouz** [comment]
technically according to [here](https://github.com/smartfog/fogflow/blob/91f4cef2690dd2c2bdff2f551f80920ccf55cdd7/worker/worker.go#L40) when you start the raspberry worker, it should get the arch type and it to the profile, and send it to the master. 
Maybe you can add a line to print this info and rebuild the worker and try to debug the issue?

**Comment by thiagopereirasilva** [comment]
I'm gonna do that. Thanks for the advice.

**Comment by showersky** [comment]
let's know if you still have some problem. This part might not be well tested.
