### ISSUE TITLE
NGSI-LD subscription not working

### ISSUE THREAD

**Issue by flaviocirillo** [smartfog/fogflow#361]
Hello,

I am trying to make a NGSI-LD subscription to the FogFlow thinBroker without success.
I am using the request available at this page Step 5: https://fogflow.readthedocs.io/en/latest/scorpioIntegration.html

`curl -iX POST \
          'http://localhost:8070/ngsi-ld/v1/subscriptions/' \
          -H 'Content-Type: application/json' \
          -H 'Integration: NGSILDBroker' \
          -H 'Accept: application/ld+json' \
          -H 'Link: <https://fiware.github.io/data-models/context.jsonld>; rel="https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"; type="application/ld+json"' \
          -d ' {
                "type": "Subscription",
                "entities": [{
                       "id": "urn:ngsi-ld:Vehicle:A106daresult",
                       "type": "daresult"
                }],
              "notification": {
                  "format": "normalized",
                  "endpoint": {
                           "uri": "http://<orion-ld-brokerIP>:1026",
                           "accept": "application/ld+json"
                   }
               }
           }'`

with the following response:
`HTTP/1.1 500 Internal Server Error
Content-Type: application/json; charset=utf-8
X-Powered-By: go-json-rest
Date: Fri, 04 Feb 2022 15:39:11 GMT
Content-Length: 76

{"Error":"invalid IRI mapping: not an absolute IRI: hybrid electric/petrol"}`

It seems there is some problem on the check of the context.json

I have tried also to change the context.json and expose it locally in order to please the check done, but I am getting the following:

`HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
X-Powered-By: go-json-rest
Date: Fri, 04 Feb 2022 15:42:51 GMT
Content-Length: 29

{"Error":"Type not allowed!"}`

**Comment by Neeraj-Nec** [comment]
Sorry @flaviocirillo ,

The doc for integration is not updated . please refer the following doc for integration 
https://github.com/smartfog/fogflow/blob/development/doc/en/source/scorpioIntegration.rst

The above doc is not merge in master. soon we will merge the doc into master branch

**Comment by naveennec** [comment]
As everything looks fine so closing this issue.
