### ISSUE TITLE
document the REST API of FogFlow with some examples

### ISSUE THREAD

**Issue by showersky** [smartfog/fogflow#363]
The REST APIs to manage FogFlow objects (operators, docker images, service topologies, fog functions, and service intents) are implemented based on raw JSON HTTP requests. It is now the time to document those APIs with some examples. Overall, this tutorial page could include the following parts: 

- REST APIs to manage FogFlow objects 
- NGSI and NGSI-LD APIs of FogFlow broker
- NGSI9 APIs of FogFlow discovery

**Comment by naveennec** [comment]
This suggestion is already implemented in below pull request.
https://github.com/smartfog/fogflow/pull/378/files

So closing this issue.
