### ISSUE TITLE
Data cannot be restored if FogFlow Broker down.

### ISSUE THREAD

**Issue by hhayashiool** [smartfog/fogflow#37]
Hi,We try to run Fogflow using "UseCase on Anomaly Detection".
I think that Fog Flow Broker manages system and user information in-memory. What is the best way to recover if a process goes down and data is lost?

**Comment by smartfog** [comment]
For the import data, it is better to issue a subscription and then save them into a persistent storage system. For example, you can trigger a subscription to forward any required data to Orion Context Broker. The current FogFlow implementation does not take care of the persistence of your data, but is rather designed to deal with real-time data.

**Comment by hhayashiool** [comment]
Thank you for replying.
