### ISSUE TITLE
Issues dynamically adding Edge Nodes

### ISSUE THREAD

**Issue by YujiAzama** [smartfog/fogflow#39]
Hi,

We are testing to increase the edge node of FogFlow in the tutorial environment.
First, we built an environment with one cloud node and one edge node, launched the Operators by define Requirements.
After that, when we added a new edge node and defined the Requirement again, Anomaly events were double-counted in Cloud Node. I guess this is because there are unnecessary operators left.
Resources of edge nodes are consumed by unwanted operators. Shouldn't unnecessary operators be removed?
It is necessary to be able to change the node configuration. Is FogFlow currently supporting the dynamic addition of Edge nodes? How can I add edge nodes it possible to fix it?

- [Operator placement before adding an edge node]
  - Cloud node
    - Count Operator
  - Edge Node1
    - Anomaly Operator

- [Actual placement of Operator after adding an edge node]
  - Cloud node 
    - Count Operator
    - Count Operator
  - Edge Node1
    - Anomaly Operator
    - Anomaly Operator
  - Edge Node2
    - Anomaly Operator
- [Expected placement of operators after adding an Edge node]
  - Cloud node 
    - Count Operator
  - Edge Node1
    - Anomaly Operator
  - Edge Node2
    - Anomaly Operator

**Comment by showersky** [comment]
please switch to the new version, which provides the intent-based programming model. The latest version can support the case to dynamically add a new edge node.

**Comment by YujiAzama** [comment]
Thank you for replying.
Please provide instructions for using the Intent-based programming model.

**Comment by YujiAzama** [comment]
Hi, @showersky 

Please let me know when the user guide for the Intent-based programming model is complete.

**Comment by showersky** [comment]
Hi Azama-san,

NTI is going to update the tutorial by the end of this week. Hopefully, you
can see the updated tutorial for the intent-based programming model early
next week.

Best regards,
Bin

**Comment by tejinderkhattra** [comment]
The tutorial is updated now.

Have a look, https://fogflow.readthedocs.io/en/latest/example1.html
