### ISSUE TITLE
NGSI10/contextEntities API has disappeared.

### ISSUE THREAD

**Issue by kiy-adachi** [smartfog/fogflow#4]
Is it right to use NGSI10/entity API instead?

**Comment by smartfog** [comment]
this belongs convenient API, only for doing some simple test. but we do not suggest the usage of those convenient APIs, since they are not standardized.

**Comment by smartfog** [comment]
in the new version, this has been changed to  NGSI10/entity

**Comment by kiy-adachi** [comment]
Ok! I understood. Thank you very much.
