### ISSUE TITLE
Cannot download Docker Image of the latest code from Docker Hub

### ISSUE THREAD

**Issue by YujiAzama** [smartfog/fogflow#40]
Hi,
I tried building with this document(https://fogflow.readthedocs.io/en/latest/edge.html#start-both-edge-iot-broker-and-fogflow-worker), but the latest image downloaded from Docker Hub doesn't seem to be the latest code on GitHub.
Is there a document with instructions for building the latest image on my local machine?
Is it possible to update the Docker Hub image in conjunction with GitHub Commit?

**Comment by showersky** [comment]
the instruction to build the code was provided before in the tutorial. You can have a look here https://fogflow.readthedocs.io/en/latest/build.html

**Comment by YujiAzama** [comment]
Thank you for your reply.

I couldn't find this link[1] in this document.
Please add this link to the side menu of the document.

[1] https://fogflow.readthedocs.io/en/latest/build.html

**Comment by tejinderkhattra** [comment]
You can now get https://fogflow.readthedocs.io/en/latest/build.html link in the side menu of Fogflow document.

Have a look,
https://fogflow.readthedocs.io/en/latest/
