### ISSUE TITLE
Cannot find documentation on how to configure "config.json"  for setting Edge Node.

### ISSUE THREAD

**Issue by hhayashiool** [smartfog/fogflow#41]
Hi, I am building a multi-node FogFlow using Raspberry Pi.
It is necessary to set "config.json" in the setting of Edge Node, but the description was not found in the document for most setting items. (e.g. site_id, start_actual_task, capacity and so on)
Is there a detailed documentation about config.son? If not, can I create a document?
I think it is important to maintain documentation so that beginners can use FogFlow.

**Comment by showersky** [comment]
I fully agree with you and I already mentioned many times to the NTI people. Hopefully, they could help on this. I do not have enough time to complete the document. Also, it is better to be documented by a user and this could make it more understandable from the user perspective.

**Comment by hhayashiool** [comment]
Thank you for replying,In your response, I understood that access control is supported in the intent-base version.
However, please tell us why the design by FIWARE-SERVICE and FIWARE-SERVICEPATH is not suitable.

Since FogFlow is a component of FIWARE, are there any interoperability problems by making it different from Orion?

**Comment by hhayashiool** [comment]
Thank you for your replying.
The users do not know how to use and write "config.json"  so we  cannot write documents.
First, the development community needs to provide a user guide

**Comment by tejinderkhattra** [comment]
User guide for config.json is updated now: https://fogflow.readthedocs.io/en/latest/edge.html
