### ISSUE TITLE
it will be nice to move FogFlow from NGSI v1 to NGSI v2

### ISSUE THREAD

**Issue by showersky** [smartfog/fogflow#42]
Since most of the other FIWARE GE now only support v2, it will be nice for FogFlow to support v2 as well. In this case, it will be easy to integrate FogFlow with IoTAgent for device integration, with WireCloud for visualization, and with QuantumLeap for saving historical data. With all these together, we can form a minimal edge computing oriented IoT platform. How do you thin? I think this does not require too much change and we can easily support it. 

@FogFlow users, how do you think? Please let me know your opinion. Do you also expect to see this feature in FogFlow?

**Comment by rahafrouz** [comment]
I like the idea, and I think it is good to be interoperable with other features. 
So for, fogflow is a framework that is self-sufficient, which is very good, but challenging when it comes to adding it to existing systems.

Most of the FiWARE users maybe start with an installation of a context broker.  
I think if we want others to start using fogflow, we should think of their perspective: How to introduce documentation for people who know the basics of context-broker, but don't know it is possible to do serverless computing of these context data!

I don't know how much NGSI-LD is adopted now, and would be adopted; maybe that would worth considering as well? 
I think FogFlow is a great platform, and if it get used by more people, it would  get more community support.

**Comment by tejinderkhattra** [comment]
For now, Scorpio Broker is being used with Fogflow to adapt to NGSI-LD.

**Comment by kox** [comment]
+1 NGSI v2

Considering that many FIWARE IoT ready devices run with NGSI v2, I think this feature is a "must".

**Comment by showersky** [comment]
thank you all for your valid feedback. I think it is necessary to make some change to support both NGSI v2 and NGSI-LD in FogFlow. I will discuss with the NTI team to see how this could be done.

**Comment by sanchitanec** [comment]
Fogflow is now supporting NGSIv2 subscription & notify, So now it is also working for WireCloud to visualize and for QuantumLeap to save historical data as well.
