### ISSUE TITLE
the scripts to run a FogFlow edge node on both normal linux node and ARM-based node

### ISSUE THREAD

**Issue by showersky** [smartfog/fogflow#46]
The provided scripts to start a FogFlow edge node must be further checked and corrected: 1) the IoT-agent is not launched right now; 2) the cadvisor is not used

**Comment by sanchita10** [comment]
In start.sh for edge broker, old port number(8082) is mentioned which should be replaced with 8070. After replacing it, its working fine.

**Comment by sanchitanec** [comment]
In start.sh for edge broker, old port number(8082) is mentioned which should be replaced with 8070. After replacing it, its working fine.

**Comment by showersky** [comment]
the deployment script for FogFlow edge node has been fixed
