### ISSUE TITLE
system monitoring

### ISSUE THREAD

**Issue by showersky** [smartfog/fogflow#48]
it will be quite useful to deploy Grafana and Prometheus to monitor the resource and tasks in the entire system.

**Comment by sanchitanec** [comment]
It is good suggestion to monitorin the resources.
We would discuss this in next weekly meeting and schedule according to the priority.

**Comment by sanchitanec** [comment]
Grafana and Elasticsearch is deployed to monitor the resource and tasks in the entire system.
