### ISSUE TITLE
firewall issue

### ISSUE THREAD

**Issue by showersky** [smartfog/fogflow#49]
Currently, the FogFlow edge node requires to have a public IP address to be accessible by the FogFlow cloud node. In the actual deployment environment, the FogFlow edge node is very often deployed behind the company firewall via NAT, we need to find a way to support this scenario. One way to address this is to find a proxy for such kind of edge nodes. For example, assign the FogFlow cloud broker to be the proxy for the FogFlow brokers at this type of edge nodes.

**Comment by sanchitanec** [comment]
Hi @showersky, All,

We would take up this feature after NGSIv-2 support.

**Comment by sanchitanec** [comment]
One level of FogFlow authentication has been achieved using FIWARE GEs Keyrock and Wilma: 
1- Web client will be authenticated before accessing FogFlow Designer on cloud node.
2- All edge node will be once authenticated by Cloud Node before starting any communication.

**Comment by showersky** [comment]
This open source VPN for edge computing seems to be a good fit to address this firewall problem. 
https://edgevpn.io/

**Comment by sanchitanec** [comment]
@showersky : it seems good. We are now working on it, after complete deployment we will address this.

**Comment by showersky** [comment]
It seems edgeVPN already provides a solution to address this problem. We leave this to advanced users to try it on their own.
