### ISSUE TITLE
persistent storage of all defined operators, service topologies, and fog functions

### ISSUE THREAD

**Issue by showersky** [smartfog/fogflow#50]
right now all initialized operators, service topologies, and fog functions are saved as NGSI entities, but they are not saved into a persistent storage file system or database. There could be three solutions to this problem: 
1) save them into some database, such as Postgresql
2) save them into some global key-value storage system, such as consul
3) save them as NGSI entities but we need to change FogFlow broker to save NGSI entities persistently (by providing some additional parameter to do this)

Personally, I think option  2) could the best choice. let's discuss about this next time.

**Comment by sanchitanec** [comment]
Hi @showersky, All,

Thank you for suggestions.
We would take up this feature after NGSIv-2 support.
