### ISSUE TITLE
prepare the release with the southbound integration

### ISSUE THREAD

**Issue by showersky** [smartfog/fogflow#51]
Since the southbound integration is ready, it will be helpful to make one release. Please consider to name the release version properly.

**Comment by showersky** [comment]
all features are worth to be rechecked before publishing the release

**Comment by sanchitanec** [comment]
ok @showersky we would well test it and release with proper versioning.

**Comment by ajayyadavnec** [comment]
it is closed https://github.com/smartfog/fogflow/releases/tag/V3.0.0.
