### ISSUE TITLE
Manual and Dashboards for System Monitoring

### ISSUE THREAD

**Issue by ajayyadavnec** [smartfog/fogflow#57]
Integration has been completed and basic functionality has been achieved but user friendly dashboard should be created and how user can monitor the solution, dashboards should be created.
 
Create manual for system Monitoring and Create dashboard for following functionality:

1. Memory and CPU monitoring
2. Message received and sent
3. Health of nodes edges and clouds
4. also explore if we can configure Alert in case of edge or cloud get unhealthy

**Comment by showersky** [comment]
could we monitor the resource usage of each instantiated FogFlow task (docker container) over each edge node?

**Comment by showersky** [comment]
please add those extra components into the docker-compose file. Can we embed the visualization page into FogFlow dashboard as a new tab?

**Comment by ajayyadavnec** [comment]
It is fixed & merged to master branch.
