### ISSUE TITLE
Contribution Guidelines for FogFlow

### ISSUE THREAD

**Issue by ajayyadavnec** [smartfog/fogflow#63]
Define the community contribution guidelines for Fogflow like other GE's
e.g
https://github.com/telefonicaid/fiware-orion/blob/master/doc/manuals/contribution_guidelines.md
https://fiware-sth-comet.readthedocs.io/en/latest/contribution-guidelines/

**Comment by Necuser1** [comment]
Done and merged in master branch.
https://github.com/smartfog/fogflow/blob/master/doc/en/source/guideline.rst

**Comment by Necuser1** [comment]
Done and merged with master branch 
link:https://github.com/smartfog/fogflow/blob/master/doc/en/source/guideline.rst
