### ISSUE TITLE
Report not generating 

### ISSUE THREAD

**Issue by Necuser1** [smartfog/fogflow#64]
testing report is not generating while testing ngsiv2

**Comment by ajayyadavnec** [comment]
![UT test Report](https://user-images.githubusercontent.com/47235345/77612385-06c61b00-6f4e-11ea-8d25-bbfc02e3e0f5.png)
Generate report like this.

**Comment by Necuser1** [comment]
Solve by merge #65 
Follow link https://github.com/smartfog/fogflow/tree/master/test/UnitTest
