### ISSUE TITLE
problem with the function postNotifyContext

### ISSUE THREAD

**Issue by showersky** [smartfog/fogflow#67]
the latest version can deal with v2 for subscribe-update-notify, but it introduced some problem with v1. please fix the problem with the flag (IsOrionBroker bool). This is an urgent problem to be fixed soon.

**Comment by ajayyadavnec** [comment]
@showersky, we would fix this ASAP.

**Comment by showersky** [comment]
sorry. This fix allows the internal subscription to work, but the integration with OrionBroker does not work. Please check!

**Comment by showersky** [comment]
I found that this is related to the URL for posting a notification. If we specify the reference URL of receiver like "/v2", the current version will not work. But If we use "/v2/op/notify", it can work. It might be related to the integration with the other v2-based component, such as wirecloud and quantumleap. If the full prefix "/v2/op/notify" is required in the subscription, please update the tutorial accordingly.

**Comment by Necuser1** [comment]
Document for this problem has been updated
