### ISSUE TITLE
Possible SQL injection

### ISSUE THREAD

**Issue by mgga** [smartfog/fogflow#7]
Hi!

Looking at the Discovery code (mainly here: https://github.com/smartfog/fogflow/blob/master/discovery/repository.go) I can see that Sprintf's are used to create the commands that are then executed against the DB.
This open's up the possibility for SQL injections. I haven't tried to attack the Discovery component but I confident that with a carefully chosen entityID (for example) one can do significant damage and/or get some data to be leaked.
This happens because the inputs are not sanitized. I will fork the repo and I'll create a pull request with a possible solution.

**Comment by mgga** [comment]
#8 Is a partial solution for this issue.

**Comment by showersky** [comment]
this has been already applied and tested in the new branch.

**Comment by showersky** [comment]
Thanks! this has been already applied and tested in the new branch, except the most complicated query.

**Comment by mgga** [comment]
@showersky thanks for including the changes! I will give it a look if I've the time.
