### ISSUE TITLE
small changes to the FogFlow tutorial

### ISSUE THREAD

**Issue by showersky** [smartfog/fogflow#73]
Some FogFlow users from The Polytechnic University of Milan shared with me their feedback in terms of  FogFlow tutorial. What they like to achieve is to develop a new FogFlow application for their own use cases, but they are confused and overwhelmed by the tutorial, because they do not have a clear idea how to design and implement their new FogFlow application. 

To address this type of confusion, one way is to provide a separated "Developer Guide" section in the FogFlow tutorial to explain how a new FogFlow application can be designed and implemented with a concrete example. We can move "intent-based programming" from the current "user guide" into a new "developer guide". The existing "user guide" will be more like a "system operator guide". 

let's discuss how we  improve the FogFlow tutorial for the developers perspective.

**Comment by sanchitanec** [comment]
Separate Developer Guide has been created in FogFLow tutorial.
